In [7]:
import torch
import torch.nn as nn
x = torch.ones(4,4,4,4)

In [12]:
### permute 维度转换
x = torch.randn(2, 3, 5)
print(x.size())
x.permute(2, 0, 1).size()

torch.Size([2, 3, 5])


torch.Size([5, 2, 3])

In [14]:
### view 视图大小改变,前提是contiguous()
x = torch.randn(4, 4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

### contiguous 返回一个内存连续的有相同数据的tensor，如果原tensor内存连续则返回原tensor

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [7]:
### meshgrid w 第三维的数据扩充 h 第二维的数据扩充
### 扩充采用复制的方式
w = torch.arange(10)
h = torch.arange(10)
x,y = torch.meshgrid(w,h)
z = torch.stack([x,y])
s = torch.flatten(z,1)
# print(w)
# print(h)
# print(x)
# print(y)
print(z)
print(s)

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
         [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
         [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
         [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
         [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
         [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
         [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
         [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]],

        [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
         [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])
tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
         4, 4,

In [12]:
### 计算
w = torch.arange(10)
print(w,w[:,None])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


In [18]:
### dot 点乘
a = torch.ones(10,10)
b = torch.ones(10)
a @ b
print(a,b, a@b)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]) tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]) tensor([10., 10., 10., 10., 10., 10., 10., 10., 10., 10.])


In [15]:
depths = [2,2,6,2]
print(sum(depth))
dpr = [x.item() for x in torch.linspace(0, 0.1, sum(depths))] 
print(dpr)


12
[0.0, 0.00909090880304575, 0.0181818176060915, 0.027272727340459824, 0.036363635212183, 0.045454543083906174, 0.054545458406209946, 0.06363636255264282, 0.0727272778749466, 0.08181818574666977, 0.09090909361839294, 0.10000000149011612]


In [9]:
a = torch.zeros(1,4,96);
nn.Parameter(a)
print(a,nn.Parameter(a))

tensor([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0.

In [20]:
w = torch.empty(3, 5)
print(w, nn.init.trunc_normal_(w))

tensor([[-1.1763,  0.0153, -0.7229, -1.3861,  1.3514],
        [-0.5460,  1.6197,  0.6402, -0.2924, -0.0674],
        [ 0.0404, -0.0387, -0.1668, -0.0761, -0.4606]]) tensor([[-1.1763,  0.0153, -0.7229, -1.3861,  1.3514],
        [-0.5460,  1.6197,  0.6402, -0.2924, -0.0674],
        [ 0.0404, -0.0387, -0.1668, -0.0761, -0.4606]])


In [2]:
assert 0 <= 15 < 14, "shift size must in 0 - 14"

AssertionError: shift size must in 0 - 14

### nn.Conv2d
$$out(N_i, C_{out_j})=bias(C_{out_j})+\sum^{C_{in}-1}_{k=0}weight(C{out_j},k)\bigotimes input(N_i,k)$$

In [ ]:
import torch
con2d = torch.nn.Conv2d(1,2,3)
m = torch.ones([2,1,3,3])
n = con2d(m)
print(m)
print(n)